apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: offmirror
  namespace: offmirror
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # Rate limiting: 10 req/s на IP, burst 20
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - data.off.wanna.community
      secretName: offmirror-tls
  rules:
    - host: data.off.wanna.community
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: offmirror
                port:
                  number: 80
