apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: offmirror
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wannagotonorway/openfoodfacts-mirror
    targetRevision: main
    path: apps/offmirror
  destination:
    server: https://kubernetes.default.svc
    namespace: offmirror
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
